### ISSUE TITLE
template updates as bot PRs

### ISSUE THREAD

**Issue by brynpickering** [arup-group/cookiecutter-pypackage#27]
### What can be improved?

As raised in https://github.com/arup-group/genet/pull/234 it's probably nicer to have the cruft template check and update done in a separate workflow and automatically raised as a new PR.

There's a dependency manager that might be updated with a bot to solve this issue for us: https://github.com/renovatebot/renovate/discussions/24000

In the meantime, we _could_ run this as its own workflow job (see below). I tried this in a boilerplate repo that I have but it comes with the issue that sometimes cruft needs to update the CI workflows themselves. This requires extra-special write permissions that can can only come from a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens). I'm not comfortable with setting up this level of write permissions for a CI action that would be deployed across all template-derived repos. So, for now, I think we wait to see if a bot comes about  

```yaml
jobs:
  cruftupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: ${{ github.event.repository.name }}-cruft
          create-args: cruft python=3.11
          post-cleanup: all
          cache-environment: true

      - name: Add dummy GitHub credentials
        run: |
          git config --global user.name Cruft check
          git config --global user.email check@dummy.bot.com

      - name: Check project against template
        id: check
        run: cruft check
        continue-on-error: true

      - name: Check on failures
        if: steps.check.outcome != 'success'
        run: cruft update -y

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Cruft - update against template
          title: Cruft - update against template
          body: |
            # Cruft - update against template

            Before you merge this PR, ensure all merge conflicts (documented in `.rej` files have been resolved)
          base: main
          labels: automated-pr, template
          branch: cruft-update
          delete-branch: true
```

### Version

v0.2.0
