### ISSUE TITLE
Ignore other .github files when triggering CI runs

### ISSUE THREAD

**Issue by brynpickering** [arup-group/cookiecutter-pypackage#32]
### What can be improved?

Changes to CI workflows should only trigger those workflows to run in PRs. E.g. PRs with changes to the docs workflow should only cause the docs workflow to run. We can do this with the `!` negator:

```
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**/*"
      - "!.github/workflows/pr-ci.yml"
```

This should ignore everything in `.github` _except_ `.github/workflows/pr-ci.yml`

### Version

v0.1.0
