### ISSUE TITLE
Split docs CI to run in PRs vs on push

### ISSUE THREAD

**Issue by brynpickering** [arup-group/cookiecutter-pypackage#33]
### What can be improved?

Building new dev docs that are pusheed to the `gh-pages` branch should happen on push to main while all other docs CI should trigger on pul requests. To fix:

```
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths-ignore:
      - tests/**
      - ".github/**/*"
      - "!.github/workflows/docs.yml"
```

### Version

v0.1.0
